//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateFromSQL.Temp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTemp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTemp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateFromSQL.Temp.ResourceTemp", typeof(ResourceTemp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT S.name AS NameS,T.name As NameT,S.name + &apos;.&apos; + T.name As  Name  FROM sys.tables T INNER JOIN sys.schemas S ON T.schema_id = S.schema_id ORDER by 3.
        /// </summary>
        internal static string GetTables {
            get {
                return ResourceManager.GetString("GetTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @TableName sysname = &apos;[TableName]&apos;
        ///
        ///declare @result varchar(max) = &apos;using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace [NameSpace]  
        ///{
        ///&apos;
        ///set @result = @result + &apos;    public class &apos; + @TableName +  &apos;
        ///    {&apos;
        ///select @result = @result 
        ///+ CASE WHEN ColumnDesc IS NOT NULL THEN &apos;
        ///        /// &lt;summary&gt;
        ///        /// &apos; + ColumnDesc + &apos;
        ///        /// &lt;/summary&gt;&apos; ELSE &apos;&apos; END
        ///+ &apos;
        ///        public &apos; + ColumnType + &apos; &apos; + ColumnName + &apos; { get; set; }&apos;
        ///from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TempGeneric {
            get {
                return ResourceManager.GetString("TempGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @TableName sysname = &apos;[TableName]&apos;
        ///declare @ClassName sysname = &apos;[TableName]&apos;
        ///
        ///--declare @TableName sysname = &apos;Articles&apos;
        ///--declare @ClassName sysname = &apos;Articles&apos;
        ///
        ///
        ///--CAPITALIZE TABLENAME  
        ///SET @TableName = UPPER(LEFT(@TableName,1)) + RIGHT(@TableName, LEN(@TableName) -1) 
        ///
        ///--SALTO DE LÍNEA  
        ///DECLARE @nl AS CHAR  
        ///SET @nl =  CHAR(10) + CHAR(13)   
        ///
        ///DECLARE @PK AS NVARCHAR(2) 
        ///DECLARE @table AS NVARCHAR(MAX) 
        ///DECLARE @column AS NVARCHAR(MAX)  
        ///DECLARE @data_type AS NVARCHAR(MAX) 
        ///DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TempGenericData {
            get {
                return ResourceManager.GetString("TempGenericData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @TableName sysname = &apos;[TableName]&apos;
        ///declare @ClassName sysname = &apos;[ClassName]&apos;
        ///
        ///declare @result varchar(max) = &apos;using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace [NameSpace]  
        ///{
        ///&apos;
        ///set @result = @result + &apos;    public class &apos; + @ClassName +  &apos;
        ///    {&apos;
        ///select @result = @result 
        ///+ CASE WHEN ColumnDesc IS NOT NULL THEN &apos;
        ///        /// &lt;summary&gt;
        ///        /// &apos; + ColumnDesc + &apos;
        ///        /// &lt;/summary&gt;&apos; ELSE &apos;&apos; END
        ///+ &apos;
        ///        public virtual &apos; + Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TempGenericEntity {
            get {
                return ResourceManager.GetString("TempGenericEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @tableName AS NVARCHAR(100)  = &apos;[TableName]&apos;
        ///DECLARE @SchemaName AS NVARCHAR(100)  = &apos;[SchemaName]&apos;
        ///DECLARE @result AS NVARCHAR(MAX)
        ///  
        ///--CAPITALIZE TABLENAME  
        ///SET @tableName = UPPER(LEFT(@tableName,1)) + RIGHT(@tableName, LEN(@tableName) -1)  
        ///  
        ///--SALTO DE LÍNEA  
        ///DECLARE @nl AS CHAR  
        ///SET @nl = CHAR(10) + CHAR(13)   
        ///  
        ///--CABECERA  
        ///DECLARE @spHeaders AS NVARCHAR(1000)  
        ///SET @spHeaders = &apos;SET ANSI_NULLS ON&apos; + @nl +  
        ///&apos;GO&apos; + @nl +  
        ///&apos;SET QUOTED_IDENTIFIER ON&apos; + @nl +  
        ///&apos;GO&apos; + @nl  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TempGenericSP {
            get {
                return ResourceManager.GetString("TempGenericSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @tableName AS NVARCHAR(100)  = &apos;[TableName]&apos;
        /// DECLARE @result AS NVARCHAR(MAX)
        ///  
        ///--CAPITALIZE TABLENAME  
        ///SET @tableName = UPPER(LEFT(@tableName,1)) + RIGHT(@tableName, LEN(@tableName) -1)  
        ///  
        ///--SALTO DE LÍNEA  
        ///DECLARE @nl AS CHAR  
        ///SET @nl = CHAR(10) + CHAR(13)   
        ///  
        ///--CABECERA  
        ///DECLARE @spHeaders AS NVARCHAR(1000)  
        ///SET @spHeaders = &apos;SET ANSI_NULLS ON&apos; + @nl +  
        ///&apos;GO&apos; + @nl +  
        ///&apos;SET QUOTED_IDENTIFIER ON&apos; + @nl +  
        ///&apos;GO&apos; + @nl +  
        ///&apos;-- =============================================&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TempGenericSP_old {
            get {
                return ResourceManager.GetString("TempGenericSP_old", resourceCulture);
            }
        }
    }
}
